### ISSUE TITLE
Support for web-config

### ISSUE THREAD

**Issue by sooslaca** [tomcz/openldap_exporter#13]
Good morning,

Would you please consider to add support for web-config.yml?
https://github.com/prometheus/prometheus/blob/main/documentation/examples/web-config.yml

That would also enable basic auth and tls

Here is how it was done in another exporter: https://github.com/hikhvar/mqtt2prometheus/commit/a25cf3f0b12af5cc5906ffea8d569aaa0401ded3

Thank you !

**Comment by tomcz** [comment]
Sure. See release v2.1.2.

**Comment by sooslaca** [comment]
just a quick feedback: it works very nice, thank you @tomcz !
