### ISSUE TITLE
[Feature request] Providing a Grafana dashboard

### ISSUE THREAD

**Issue by croessner** [tomcz/openldap_exporter#19]
Hello,

thank you very much for your exporter! I finally installed it on my primary OpenLDAP-server and have integrated it into Prometheus. Does somebody have a working Grafana dashboard and would like to add it here to a contrib folder? That would be really nice.

Thanks in advance.

**Comment by tiago-cruz-movile** [comment]
Hello @croessner , do you have something to share? :)

**Comment by azdfzshffg** [comment]
Hello ,

@croessner  Do you have a dashboard ?

It would be nice to have a dashboard fort this great exporter :)


Thanks all

**Comment by vladimir9876** [comment]
[OpenLDAP.txt](https://github.com/tomcz/openldap_exporter/files/11011965/OpenLDAP.txt)
this one works for me

**Comment by azdfzshffg** [comment]
really good , thanks a lot.

Maybe you add this dashboard on contrib folder
