### ISSUE TITLE
Question about replicationObject parameter

### ISSUE THREAD

**Issue by tiago-cruz-movile** [tomcz/openldap_exporter#25]
Hello,

```
$ ldapsearch -LLL -x -H ldaps://xxxx -b dc=datac,dc=xxx,dc=com -D uid=xxxxx -w xxxx -s base contextCSN
dn: dc=datac,dc=xxx,dc=com
contextCSN: 20230104171052.895118Z#000000#001#000000
contextCSN: 20230106202836.142061Z#000000#00b#000000
```

I'm running with `-replicationObject "dc=datac,dc=xxx,dc=com"` parameter

And I'm getting this output from exporter:

```
$ curl -s http://localhost:9330/metrics  | grep -v \# | grep replication
openldap_monitor_replication{id="001",type="count"} 0
openldap_monitor_replication{id="001",type="gt"} 1.672855957e+09
openldap_monitor_replication{id="001",type="mod"} 0
```
The questions are:

1-) I'm interested to get information about `#00b#` and not `#001#` is this possible?

2-) Is this graph the expected result?

expr `sum(openldap_monitor_replication) by (instance, dn)>0`

![image](https://user-images.githubusercontent.com/4048174/211603227-5f64c9c2-e55a-4edd-92c9-efe25ffcebab.png)

3-) The `"count"` or `"mod"` supposed to increase somehow?

![image](https://user-images.githubusercontent.com/4048174/211603793-61e8c069-70a6-45da-8cf6-46cc7ab5c14c.png)

4-) What the `"gt"` metric means?

Thanks

**Comment by JGodin-C2C** [comment]
hello, 
This seems to be a miss-understanding of the value returned by this exporter. It only report the values that openldap gives it . You can have more information about this here : 

https://www.openldap.org/faq/data/cache/1145.html

`
1-) I'm interested to get information about #00b# and not #001# is this possible?`

It is hard for me to understand your montage and thus cannot really answer your question.

**Comment by x11tete11x** [comment]
@tiago-cruz-movile did you find something about what is that "gt" value?, i'm facing the same and looks like it's not the same as:

`ldapsearch -H ldaps://ldap-mydomain.net -D "cn=xxxxxx,cn=xxxxx" -W -b "dc=myorg,dc=net" -s base contextCSN`

**Comment by x11tete11x** [comment]
Hi!, found it, it's in epoc time you can query by doing the following:

`openldap_monitor_replication{type="gt"}*1000`


Then you will get something like this:

![image](https://user-images.githubusercontent.com/2127236/220675934-34c1c0cf-a248-4f23-8a1d-f33904c521ed.png)

**Comment by JGodin-C2C** [comment]
As documented here : 
https://www.openldap.org/faq/data/cache/1145.html
...
